In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [20]:
df = pd.read_csv('data_set/salaries.csv')
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [21]:
print(df.columns)

Index(['company', 'job', 'degree', 'salary_more_then_100k'], dtype='str')

In [22]:
dummies = pd.get_dummies(df[['company', 'job', 'degree']], drop_first=True)
dummies.head()

,company_facebook,company_google,job_computer programmer,job_sales executive,degree_masters
0,False,True,False,True,False
1,False,True,False,True,True
2,False,True,False,False,False
3,False,True,False,False,True
4,False,True,True,False,False

In [30]:
inputs = pd.concat([df.drop(['company', 'job', 'degree', 'salary_more_then_100k'], axis='columns'), dummies], axis='columns')
target = df['salary_more_then_100k']
inputs.head()

,company_facebook,company_google,job_computer programmer,job_sales executive,degree_masters
0,False,True,False,True,False
1,False,True,False,True,True
2,False,True,False,False,False
3,False,True,False,False,True
4,False,True,True,False,False

In [49]:
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2, random_state=42)

from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(X_train, y_train)
print("Train Model Score:", model.score(X_train, y_train))
print("Test Model Score:", model.score(X_test, y_test))

Train Model Score: 1.0
Test Model Score: 0.25

In [ ]:
model.fit(inputs, target)
print("Score on whole data:", model.score(inputs, target))

Model Score: 0.25
Score on whole data: 1.0

In [10]:
model.predict([[2, 2, 1]])

d:\Web-Dev\Learn Machine Learning\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])